# U 输入法的精简 Rime 默认配置
# encoding: utf-8

config_version: "1.0"

schema_list:
  - schema: rime_frost
  - schema: rime_frost_double_pinyin_flypy

menu:
  page_size: 7

switcher:
  caption: 输入方案
  hotkeys:
    - Control+grave
  save_options:
    - ascii_mode
    - full_shape
    - ascii_punct
  fold_options: true
  abbreviate_options: true

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Shift_L: commit_code
    Shift_R: noop
    Control_L: noop
    Control_R: noop

key_binder:
  bindings: []

punctuator:
  full_shape:
    " ": { commit: "　" }
    ",": { commit: ， }
    ".": { commit: 。 }
    "?": { commit: ？ }
    "!": { commit: ！ }
    ":": { commit: ： }
    ";": { commit: ； }
    "'": { pair: [ ‘, ’ ] }
    '"': { pair: [ “, ” ] }
    "(": （
    ")": ）
    "[": 【
    "]": 】
    "<": [ 《, 〈 ]
    ">": [ 》, 〉 ]
    "/": [ 、, ／ ]
    "\\": ＼
    "-": －
    "_": ——
  half_shape:
    ",": { commit: ， }
    ".": { commit: 。 }
    "?": { commit: ？ }
    "!": { commit: ！ }
    ":": { commit: ： }
    ";": { commit: ； }
    "'": { pair: [ ‘, ’ ] }
    '"': { pair: [ “, ” ] }
    "(": （
    ")": ）
    "[": 【
    "]": 】
    "<": [ 《, 〈 ]
    ">": [ 》, 〉 ]
    "/": [ 、, "/" ]
    "\\": "\\"
    "-": "-"
    "_": ——
